spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/reco
#  data:
#    redis:
#      host: redis
#      password: reco1234
#      port: 6379