spring:
  application:
    name: reco

  profiles:
    include: auth
    active: prod


  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace