spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/reco

  data:
    mongodb:
      uri: mongodb+srv://ADMIN:SSAFY123@reco.mv9rf.mongodb.net/RECO?ssl=true
    redis:
      host: localhost
      port: 6379
      password:

  neo4j:
    uri: neo4j+s://8295f96d.databases.neo4j.io
    authentication:
      username: neo4j
      password: O2TxuKNhWqOcpfD1mBwtuqDgOjL6lcyN3osgzuUSiTo
  jackson:
    default-property-inclusion: always